version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t package

  build:
    commands:
      # Build index-photos zip
      - echo Packaging index-photos Lambda...
      - mkdir -p build/index-photos
      - cp -r package/* build/index-photos/
      - cp INDEX-PHOTOS/index-photos.py build/index-photos/lambda_function.py
      - cd build/index-photos && zip -r ../../index-photos.zip . && cd -

      # Build search-photos zip
      - echo Packaging search-photos Lambda...
      - mkdir -p build/search-photos
      - cp -r package/* build/search-photos/
      - cp INDEX-PHOTOS/search-photos.py build/search-photos/lambda_function.py
      - cd build/search-photos && zip -r ../../search-photos.zip . && cd -

  post_build:
    commands:
      - bash buildspec_update_lambda_code.sh

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
