version: 0.2

phases:
  install:
    commands:
      - echo Skipping dependency installation, not needed.

  build:
    commands:
      # Build index-photos zip
      - echo Packaging index-photos Lambda...
      - mkdir -p lambdas/build/index-photos
      - cp lambdas/index-photos.py lambdas/build/index-photos/lambda_function.py
      - cd lambdas/build/index-photos && zip -r ../../../index-photos.zip . && cd -

      # Build search-photos zip
      - echo Packaging search-photos Lambda...
      - mkdir -p lambdas/build/search-photos
      - cp lambdas/search-photos.py lambdas/build/search-photos/lambda_function.py
      - cd lambdas/build/search-photos && zip -r ../../../search-photos.zip . && cd -

  post_build:
    commands:
      - bash buildspec_update_lambda_code.sh

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
